### ISSUE TITLE
API gives unrounded time measurements

### ISSUE THREAD

**Issue by pylessard** [scrutinydebugger/scrutiny-python#64]
times samples may look like this

```
   22.36,
            22.38,
            22.400000000000002,
            22.42,
            22.44,
            22.46,
            22.48,
            22.5,
            22.52,
            22.54,
            22.56,
            22.580000000000002,
            22.6,
            22.62,
            22.64,
            22.66,
            22.68,
            22.7,
            22.72,
```

**Comment by fredericmorin** [comment]
This is fine. Its up to the UI to make numbers looks pretty to humans.

**Comment by pylessard** [comment]
hmmm, not just a matter of being nice to the human. But float precision is a computation artifact, the external world shouldn't know about the internal limitation of the server.  

The most common use case is someone exporting the graph to excel and then getting weird display and non-uniform time sampling. I think it's worth cleaning at least a minimum at the server/api level.

**Comment by pylessard** [comment]
Fixed here : https://github.com/scrutinydebugger/scrutiny-python/commit/581c6a5fa9f880d5577c282e4aaf4e3612a345b6
